### PR TITLE
Reduce unused and uninitialized variables warnings

### PR DESCRIPTION
**Pull request by darealshinji**

### CODE REVIEW

**Comment by tedsmith** [comment]
It might be a few days before I get chance to look at this one more thoroughly because I'm going away with friends until the middle of next week. But I'll look when I get back but it may be a week or two before I respond. Thanks as always for your input and ideas with this, and for adding for the various labels to the issues already submitted...makes it much clearer.

**Comment by tedsmith** [comment]
@darealshinji - Oh no man...I'm sorry! I made quite a few changes today having forgot I was still to look at this and merge it. So I pushed my last commit and then realised the changes will clash with the changes you have here. So obviously the master branch is still OK, but I'm not sure how possible it is to incorporate your improvements to the commit just submitted? I realise I should have checked your patch and merged it first but I totally forgot.

**Comment by darealshinji** [comment]
Merge conflicts are now resolved.

**Comment by tedsmith** [comment]
OK, I gave this a whirl and though it is much improved over the previous commit, there's an issue still when viewing the technical data of a disk. 

After some considerable debugging, I narrowed it down to the uGPT.pas file, specifically the following lines : 

144 is now  FillChar(Data4Array{%H-}, 8, 0); but was   FillChar(Data4Array, 8, 0);
168 as above
220 has an invalid use of string(@PartitionLabel) instead of WideCharToString(@PartitionLabel)
365 has  FillChar(ProtectiveMBR{%H-}, SizeOf(ProtectiveMBR), 0); instead of FillChar(ProtectiveMBR, SizeOf(ProtectiveMBR), 0);

I think if you correct (revert) those, especially the string\widechartostring line, hopefully then we can merge the commit.

**Comment by darealshinji** [comment]
The `{%H-}` is just to silence the compiler and _should_ not do any harm. Does it work as intended if you only revert the `WideCharToString()` part?

**Comment by tedsmith** [comment]
Yeah, its the string thats the problem. Converting String(@PartitionLabel);  to WideCharToString(@PartitionLabel); works fine :-) 

To keep things simple, is it easier for you to adjust the pull request?

**Comment by darealshinji** [comment]
What do you mean? The pull request in its current form doesn't change `uGPT.pas` at all.

**Comment by tedsmith** [comment]
Oh yeah! Erm, so where did these changes come from? I'm proper confused now!

**Comment by darealshinji** [comment]
An older PR that was merged: https://github.com/tedsmith/quickhash/commit/df10c8c5c003ef35332bfc256d674981249f20dd

**Comment by darealshinji** [comment]
Wait, doesn't https://github.com/tedsmith/quickhash/commit/44fb52a3cea5abab254feca6617c61b9c5dab49d actually revert all the changes from this PR?

**Comment by tedsmith** [comment]
Mmmm, how very confusing. It looks like it, but that wasn't my intention. This isn't going well. I'm starting to dislike git! :-( How can we restart the pull request?

**Comment by darealshinji** [comment]
Now that it's merged I guess I have to do a new PR. Or you apply the changes manually to your source code.

**Comment by tedsmith** [comment]
I managed to find your version of uGPT.pas that I'd copied to a folder along with the 2.8.2 version of the file because I was using Notepad++ to compare them. So I just applied the "string(..." to "WideCharToString(.." adjustment and then committed that file to master. So at least that's one of the files from your PR done. I don't think I have the others though.

**Pull request merged**
