### PR TITLE
Linux: build with Makefile, fix taskbar icon, use udevadm not /sbin/u…

### PR DESCRIPTION
**Pull request by darealshinji**
…devadm

### CODE REVIEW

**Review by tedsmith — COMMENTED** [review]
Removing diskspecification in uses will make it failed to compile on Windows and it is (now) required for both Win and Linux. I've re-added diskspecification.lfm to hopefully enable building now with Makefile?

**Comment by tedsmith** [comment]
You are right that the git code checkout didn't fully compile ebcause of a missing pas and a missing lfm. I've now added those two, too. Having added them, I able to compile, launch (as sudo) and hash a disk.

**Comment by tedsmith** [comment]
@darealshinji - with the latest commit to master, are you able to confirm if building is now possible? It seems to be on my system now.

**Comment by darealshinji** [comment]
> On my system, udevadm is in /sbin/udevadm. If we change it to "udevadm...", on my system, it says it cant find it.

I guess `/sbin` isn't in `PATH` by default then, otherwise it would work I guess. On some Ubuntu versions it's only in `/bin/udevadm` so using an absolute path is not realiable on all Linux distros.

**Comment by tedsmith** [comment]
I've deleted the binary which you correctly identified had sneaked in there. 

I've re-added the quickhash_linux.lpi file that Git is telling me it is now conflicting with this pull request, so I'm not sure whether that is resolvable or not. I went to "resolve conflicts" but there doesn't seem to be a button to accept or reject. All I changed was the (c) year and the title value. I'm not sure why we have that file though? Is it needed for the makefile? It suggests we need a different lpi for Linux but I always just use the main one for all 3 platforms.

**Comment by darealshinji** [comment]
Conflicts should now be resolved. Yes, I think the separate lpi was needed to be able to build with Makefile out of the box.

**Pull request merged**
