### PR TITLE
Reducing compiler warnings

### PR DESCRIPTION
**Pull request by darealshinji**
I was trying to reduce compiler warnings. Please have a look at this, since I don't have much experience with pascal.

### CODE REVIEW

**Comment by tedsmith** [comment]
These look like very promising improvements Dareal. Before I merge into master though, do you know how I can pull down this pull request to test it out? Forgive me - when it comes to anything more than fetch, pull, commit and push I get a bit muddled with git!

**Comment by darealshinji** [comment]
You can download it from my repository using git:
```
git clone https://github.com/darealshinji/quickhash
cd quickhash
git checkout compiler-warnings
```

Or you download it directly from Github:
```
https://github.com/darealshinji/quickhash/archive/compiler-warnings.zip
https://github.com/darealshinji/quickhash/archive/compiler-warnings.tar.gz
```

By the way my name isn't "Dareal". "Darealshinji" is just a nickname I use; da real Shinji = the real Shinji, and no my name isn't "Shinji" either. Another nick I often use is "djcj".

**Comment by tedsmith** [comment]
...hang on...there's an issue with the listing of logical drives (C:\, D:\ etc) in the disk module. v2.8.2 lists them, but with this merge, it does not. I think it has something to do with ListDrives and the conversion of  DeviceID to string sintead of widestring....am looking into it

**Comment by tedsmith** [comment]
yes...reverting DeviceID, s : string; to DeviceID, s : widestring;    on line 1614 corrects the problem. Its because of the Windows API which needs a widestring.

**Comment by tedsmith** [comment]
...and there's a further issue. The handle initiation fails even when run as administrator. But v2.8.2 works OK. I suspect the same solution will be there...I'll look into that too

**Comment by tedsmith** [comment]
...and right clicking a disk and choosing the "Show disk technical data" fails. The sector counts and exactdisksize values etc are needed for that. I think I perhaps need to revert the diskmodule.pas file because the changes seem to have adversely effected much of the disk hashing module. What do you think?

**Comment by tedsmith** [comment]
Yes, the SelectedDrive value is all messed up : 

image

**Comment by darealshinji** [comment]
Sorry, I should have checked it more thoroughly. I'd say, revert `diskmodule.pas` and then manually apply only the safe changes from my commit.

**Pull request merged**
